// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZTa8bafYX43B0m0DntC7zK7Y0PF-yxjQ',
    appId: '1:117790615706:web:b39804a5f68bcba0661723',
    messagingSenderId: '117790615706',
    projectId: 'codelab3-4d9f5',
    authDomain: 'codelab3-4d9f5.firebaseapp.com',
    storageBucket: 'codelab3-4d9f5.appspot.com',
    measurementId: 'G-65P12YS3FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOO6Yxr4WHa2EabrSICcwv0WL0tBlaK8',
    appId: '1:117790615706:android:6e94b9e435878083661723',
    messagingSenderId: '117790615706',
    projectId: 'codelab3-4d9f5',
    storageBucket: 'codelab3-4d9f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSmS208KRVyaBt1xumv7RJPs3PKdKEEM',
    appId: '1:117790615706:ios:dbb524d00e5cdfe8661723',
    messagingSenderId: '117790615706',
    projectId: 'codelab3-4d9f5',
    storageBucket: 'codelab3-4d9f5.appspot.com',
    iosBundleId: 'raihanrr400gmail.com.codelab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKSmS208KRVyaBt1xumv7RJPs3PKdKEEM',
    appId: '1:117790615706:ios:dbb524d00e5cdfe8661723',
    messagingSenderId: '117790615706',
    projectId: 'codelab3-4d9f5',
    storageBucket: 'codelab3-4d9f5.appspot.com',
    iosBundleId: 'raihanrr400gmail.com.codelab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZTa8bafYX43B0m0DntC7zK7Y0PF-yxjQ',
    appId: '1:117790615706:web:eee2718ad11697d0661723',
    messagingSenderId: '117790615706',
    projectId: 'codelab3-4d9f5',
    authDomain: 'codelab3-4d9f5.firebaseapp.com',
    storageBucket: 'codelab3-4d9f5.appspot.com',
    measurementId: 'G-1VD2JL38J4',
  );
}
